name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: apisolid
        options: >-
          --health-cmd "pg_isready -U docker"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          NODE_ENV: test
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
        timeout-minutes: 10
